repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--sort-inputs-by-required=true
          - --hook-config=--sort-outputs-by-required=true

      - id: terraform_tflint
        args:
          - --args=--disable-rule=terraform_required_version
          - --args=--disable-rule=terraform_required_providers
      - id: terraform_tfsec


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
